### ISSUE TITLE
createElement not working.

### ISSUE THREAD

**Issue by vzRowan** [bavix/advanced-html-dom#11]
In the SimpleHTMLDom documentation i found a method called "createElement". It allowed you to make an element and place it in the html with making use of some other methods. However, i am experiencing some issues, that be, it just doesn't work.

So, if this is not an option, how can i create an HTML Element, and place it after the element i have selected?

**Comment by rez1dent3** [comment]
@vzRowan 
Hello. In this fork, I did not add new functionality, but only fixed bugs https://github.com/monkeysuffrage/advanced_html_dom and memory leaks. Unfortunately, the original package does not and did not have a creation method.
