### ISSUE TITLE
Is there a non-composer version?

### ISSUE THREAD

**Issue by LeninZapata** [bavix/advanced-html-dom#14]
Hello, I have the original library whose repository no longer exists. The detail is that it was the Non-Composer version. My project called it directly from a file and then instantiated it and did everything. Unfortunately, this version has some errors and I want to update to your corrected version, but it is in Composer and it is complicated because my project does not use Composer.

**Comment by LeninZapata** [comment]
I merged all the files into 1 file, then ran a simple example and got the same errors as the original author "should either be compatible with" 

```
<?php
require_once 'advanced-html-dom/src/one.php';


$dom = new \Bavix\AdvancedHtmlDom\AdvancedHtmlDom();

$dom->loadFile('https://fical.net/es/calculadora-de-inter%C3%A9s-compuesto');

foreach ($dom->find('img') as $img)
{
    var_dump($img->attributes());
}
```

![image](https://github.com/user-attachments/assets/986af73b-822a-4c0a-a40f-6b0155f559f1)

**Comment by LeninZapata** [comment]
Reopen

**Comment by rez1dent3** [comment]
Hello. Unfortunately, the project has not been supported for more than 5 years. If anyone wants to take over the support, then I will give the appropriate rights to the repository. This project only supports php 7.x, there is no php 8 support here. Judging by your errors, you have php 8.2+

**Comment by LeninZapata** [comment]
I understand, thank you very much for the clarification, so it was because of my PHP version. I'm going to make a fork to later make this update and correct these messages that appear when I activate Debug.
